# Generated by Django 5.2.5 on 2025-08-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_image_supplier_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
