# Generated by Django 5.2.5 on 2025-08-10 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='supplier',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'employee'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
